### ISSUE TITLE
Vectors

### ISSUE THREAD

**Issue by bartsnapp** [mooculus/calculus3#1]
\vec has been re-defined to be bold faced; however, we still want the functionality of \vec to illustrate that sometimes people do use an arrow above the letter. 

I've done this wrong but it needs to be fixed.

**Comment by QueerFunctor** [comment]
Has this been done by giving the \vec command options? Like \vec{something} yielding \vec with the arrow?
________________________________

**Comment by bartsnapp** [comment]
No - \vec has no options. If it did, it would be \vec[arrow]{v} or \vec[bold]{v} or some such. At the moment, there are no plans to do this.
