### ISSUE TITLE
Question is not a question

### ISSUE THREAD

**Issue by Shusako** [mooculus/calculus3#10]
This is for the Calculus and Vector-Valued Functions page, the direct link to report an issue of content is not working.

There are several sections labeled as questions that do not have any input boxes, but rather just the answer to the question right there. This could be intentional, but if it is I believe the sections should be labeled as an example, instead of a question.

**Comment by bartsnapp** [comment]
Ah! Yes - more "answers" were needed. I've changed it. If you've completed the activity, you don't need to do the extra problems (but you can).
