### ISSUE TITLE
Lines and curves in space

### ISSUE THREAD

**Issue by 11152016** [mooculus/calculus3#2]
At the bottom of the page, two implicit eqns are given!

See [linesAndCurvesInSpace/digInLinesAndCurvesInSpace.tex](https://github.com/mooculus/calculus3/blob/357f83dbb55e4616a22ff6bd17d97b8f3e949fcd/linesAndCurvesInSpace/digInLinesAndCurvesInSpace.tex)

**Comment by bartsnapp** [comment]
Fixed at the source. Copy-paste error. Will be fixed next time we deploy.
