### ISSUE TITLE
Integrals  with  trivial                                                                                                                                    integrands

### ISSUE THREAD

**Issue by haochen3611** [mooculus/calculus3#4]
See [multipleIntegrals/digInIntegralsWithTrivialIntegrands.tex](https://github.com/mooculus/calculus3/blob/a08054a7c1858f87e42e17385ed04b86c01e0ee6/multipleIntegrals/digInIntegralsWithTrivialIntegrands.tex)

The last problem
 \int_{\answer{-\sqrt{z^2-y^2}}}^{\answer{\sqrt{z^2-y^2}}}
The boundary for x should be -sqrt((1-z)^2-y^2) to sqrt((1-z)^2-y^2).

**Comment by bartsnapp** [comment]
Fixed!
