### ISSUE TITLE
Polar coordinates

### ISSUE THREAD

**Issue by haochen3611** [mooculus/calculus3#5]
See [commonCoordinates/digInPolarCoordinates.tex](https://github.com/mooculus/calculus3/blob/808edb2087154ea2b063a22aa776a9a7177f5208/commonCoordinates/digInPolarCoordinates.tex)

Hello, 

There are a few problems I found while I was doing the exercises. 

1. 
Under the first question 
(r,\theta) = (\answer{\sqrt{26}}, \answer{\arctan(5)-\pi})

Theta should be arctan(5)+n*pi, where n is an odd integer.  

2. 
  = \answer{5\pi/8}

integral = pi*0.5^2/8*(5+5+4+2)+pi*(1^2-0.5^2)/8*(1+0+(-1)+(-3))=7/32*pi

3. 
\answer[given]{\frac{-2}{6}(a^2-r^2)^{3/2}}

It should be -2/3(a^2-r^2)^(3/2)

**Comment by bartsnapp** [comment]
Hi,

for your first one, I've restricted the domain requested in the answer.

For 2 and 3, please check your computation. I've double checked, and it seems that you are in error.

**Comment by bartsnapp** [comment]
Oh I see - for 3, I pulled out a 2! Fixed.
