### ISSUE TITLE
Computations And Interpretations

### ISSUE THREAD

**Issue by haochen3611** [mooculus/calculus3#6]
Hi, 

and this inequality then implies that
  \[
  \left| \int_T 2 \sin (x^2) \d A \right| \leq \left| \int_T 2 \d A \right| \answer{\pi^2}.
  \]
  So $1.9$ is certainly in the ballpark of plausibility.

There might be a "=" missing between  \right| and \answer{\pi^2}.

**Comment by bartsnapp** [comment]
Absolutely! Thanks. Fixed.
