### ISSUE TITLE
Vectors

### ISSUE THREAD

**Issue by JukeboxRhino** [mooculus/calculus3#8]
There's a chance I'm being dumb, but I can't seem to find why this would not be the correct answer.
![Image of issue](http://i.imgur.com/bgTX9mF.png)
See [vectors/digInVectors.tex](https://github.com/mooculus/calculus3/blob/1c98119d4680d191909d84ec6c8da79486d12223/vectors/digInVectors.tex)

**Comment by JukeboxRhino** [comment]
I'm only having an issue on three questions, but they are the only ones that use `\cdot` inside an `answer{}` block. I'm not sure whether I am not getting the questions and it's a coincidence or something else. On lines [443](https://github.com/mooculus/calculus3/blob/master/vectors/digInVectors.tex#L443), [450](https://github.com/mooculus/calculus3/blob/master/vectors/digInVectors.tex#L450), and [558](https://github.com/mooculus/calculus3/blob/master/vectors/digInVectors.tex#L558)

**Comment by bartsnapp** [comment]
This must be a validation issue with \cdot
