### ISSUE TITLE
Incorrect graph

### ISSUE THREAD

**Issue by Shusako** [mooculus/calculus3#9]
See [linesAndCurvesInSpace/digInLinesAndCurvesInSpace.tex](https://github.com/mooculus/calculus3/blob/1c0679aa57e4bc8a45946be7380ab64caf29d86c/linesAndCurvesInSpace/digInLinesAndCurvesInSpace.tex)

For the question display the graph of x^2+y^2=z^2+1, the graph is incorrect. When z = 0, it should be a circle of radius 1 in the x-y plane, but that is not shown.

**Comment by bartsnapp** [comment]
Ah. The axis were mislabled. Fixed. Redeploying right now. Will be done by 9:15am 1/23/17
